In [73]:
import numpy as np
np.array([[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [74]:
np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [76]:
np.random.rand(2,3)

array([[0.17258044, 0.59965044, 0.37345455],
       [0.07825475, 0.57080934, 0.59985745]])

In [77]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [78]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [79]:
np.eye(3,k=-1) + np.eye(3,k=1)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

In [80]:
np.arange(2,100,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [81]:
np.linspace(2,98,25)

array([ 2.,  6., 10., 14., 18., 22., 26., 30., 34., 38., 42., 46., 50.,
       54., 58., 62., 66., 70., 74., 78., 82., 86., 90., 94., 98.])

In [82]:
a = np.array([[[1,2]],[[2,1]]])
print("( ", end="")
for x in range(a.ndim):
    print(a.shape[x],end =" ")
print(")")
print(a)
print(a.size)

( 2 1 2 )
[[[1 2]]

 [[2 1]]]
4


In [83]:
b = np.array([1,2,3,4,5,6])
c = np.reshape(b,(3,-1))    # -1 gets calculated automatocally to fit the data.
d = np.reshape(b,(2,-1))
print(c)
print(d.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [88]:
p = np.array([[1,2],[2,3]])
q = p.ravel()
print(p,"\n",q)

[[1 2]
 [2 3]] 
 [1 2 2 3]


In [92]:
def dims(a):
    print("( ", end="")
    for x in range(a.ndim):
        print(a.shape[x],end =" ")
    print(")")

In [96]:
x = np.array([[[[1,2]],[[1,2]]]])
y = np.squeeze(x)
dims(x)
dims(y)
print(x,"\n",y)

( 1 2 1 2 )
( 2 2 )
[[[[1 2]]

  [[1 2]]]] 
 [[1 2]
 [1 2]]


In [103]:
e = np.array([1,2,3,4,5,6])
print(e[1:5:2])

[2 4]
